### PR TITLE
DM-24616: Do not try to open calib sqlite file if it does not exist

### PR DESCRIPTION
**Pull request by timj**
Opening it causes sqlite3 to create the file.  This is rude but
also breaks when the input gen2 repo is read only.

### CODE REVIEW

**Comment by timj** [comment]
We know we definitely are doing that because that's why we found the problem. Maybe what you are saying is that the obs_lsst convert tests are misconfigured (it's clear that the "root" is also not set to a calibration repository).

**Comment by TallJimbo** [comment]
> Maybe what you are saying is that the obs_lsst convert tests are misconfigured (it's clear that the "root" is also not set to a calibration repository).

Yup, that's it - it looks like the test code in obs_base doesn't do the right thing if the `gen2calib` class attribute isn't overridden, and obs_lsst doesn't override it.

I can't resist saying that this is one more example of why "override class attributes" is antipattern that should be replaced by `@abstractmethod` whenever possible, though I may be preaching to the choir on that.

**Comment by timj** [comment]
Thanks. I'm fixing it and will get back to you.

**Comment by timj** [comment]
Oh, the first f-string shouldn't be an f-string 😄

**Comment by timj** [comment]
Hmm. Okay, I think a new flake8 has been released. The format warning is totally legitimate so I've fixed them.

**Pull request merged**
